### ISSUE TITLE
Some issues with this.ds.cloneWithRowsAndSections

### ISSUE THREAD

**Issue by Thorbenandresen** [jemise111/react-native-swipe-list-view#10]
Hi Jesse,

I am using cloneWithRowsAndSections according to [this simple tutorial](https://medium.com/@darylrowland/reactnative-listview-with-section-headers-99a6714282c3#.h5fhpy1m3) but `cloneOnPress` and the "manually closing rows" does only work on my last section. 

Thanks!

**Comment by jemise111** [comment]
@Thorbenandresen good call, wasn't accounting for sectionIds, only rowIds. Fixed by #13. Will be released with v0.1.0. Please note this introduced a small breaking change for the manually closing rows functionality that we discussed here: https://github.com/jemise111/react-native-swipe-list-view/issues/7. See the README and example for the change. It's very small. Let me know if you have any questions or issues, thanks!
