### ISSUE TITLE
npm WARN react-native-swipe-list-view@0.4.1 requires a peer of react@>=0.14.8 but none was installed.

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#126]
Can we removed [this](https://github.com/jemise111/react-native-swipe-list-view/blob/master/package.json#L25) dependency from the build?  I don't think it's valid.

**Comment by jemise111** [comment]
@npomfret Sorry for the delay in responding. Is this still an issue? 

If anyone is using the package inside of a react-native project they should definitely have react-native and react installed so I don't see why they would have that warning. And since this package does `import { Component } from 'react'` it is indeed a peer dependency

**Comment by jemise111** [comment]
I don't believe this is an issue anymore
