### ISSUE TITLE
useNativeDriver: true ?

### ISSUE THREAD

**Issue by grubstarstar** [jemise111/react-native-swipe-list-view#135]
I noticed that none of the Animations use the `useNativeDriver: true`. I was just wondering if you had tried this and if it improves the animations?

http://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

**Comment by jemise111** [comment]
@grubstarstar Good call, done! via #162

**Comment by jemise111** [comment]
Hey @grubstarstar turns out this change actually had a nasty side effect and I had to revert it.

This package highly depends on being able to track the value of an `Animated.Value`. Unfortunately animating an Animated.Value with `useNativeDriver` set to `true` causes the internal `_value` to often be wrong.

So as long as people aren't seeing bad perf without the animations using the native driver I'm going to need to keep this flag turned off.

**Comment by grubstarstar** [comment]
Ah okay, no worries. Thanks for trying it out though.
