### ISSUE TITLE
Windows: Swiping not working when vertical scrolling enabled on the list

### ISSUE THREAD

**Issue by juanjo-ramos** [jemise111/react-native-swipe-list-view#145]
I'm consistently seen the following problem:
If the total number of rows can fit in the visible screen and or if they can't but scrolling is disabled on the underlying List, the horizontal swiping works as expected.

However, as soon as vertical scrolling is enabled the swiping doesn't work anymore when interacting with the finger. Using the mouse or a stylus makes the swipe work as expected as well.

**Comment by jemise111** [comment]
Hey @juanjo-ramos I haven't heard of this issue before. I'm a little confused.. is this only happening on emulators or on device as well? I only ask because you mentioned using a mouse. 

If you have some example code to repro the issue that'd be really helpful and I'd be happy to take a look, thanks!

(Sorry for the delay in responding)

**Comment by ethanx94** [comment]
I have the same when nesting SwipeListView within a ScrollView. It seems as if the ScrollView is taking priority for only touch events but yet not mouse events.

**Comment by jemise111** [comment]
@ethanx94 is it completely necessary to nest the SwipeListView in a ScrollView? Can you make use of the `header` and `footer` for extra content and not use a ScrollView at all?

And then I'm a bit confused when you say "mouse events". Is this a problem only on an emulator?

Thanks!

**Comment by jemise111** [comment]
@ethanx94 Awesome job finding that fix, thanks for doing the research on this!

**Comment by jemise111** [comment]
Fixed in v1.1.1

**Comment by matheusbaumgart** [comment]
> I have the same when nesting SwipeListView within a ScrollView. It seems as if the ScrollView is taking priority for only touch events but yet not mouse events.

I'm also using it nested within a ScrollView and the any vertical scrolling, after starting the swipe action aborts the "swipe".

**Comment by VitaliiK91** [comment]
@jemise111 I am experiencing similar issue in iOS. If list is not scrolled (or is at the very top) swiper works just perfect. But once list is scrolled even slightly swiping functionality stops working. It lets you start the swipe gesture but forces row to close right away. Any ideas what might cause it? Thanks you!

**Comment by jemise111** [comment]
@VitaliiK91 This is a tough one for me to debug as I don't have Windows.

I suspect the issue is that the parent ScrollView is becoming the responder for all gesture handler and the SwipeListView is not receiving touch events. Can you remove the ScrollView entirely and just use the SwipeListView's header and footer to render the rest of your content?

This may help as well: https://stackoverflow.com/questions/51098599/flatlist-inside-scrollview-doesnt-scroll

**Comment by VitaliiK91** [comment]
@jemise111 Thanks for the quick response. Mine is actually not windows, but iOS (both simulator and actual device) I don't have it wrapped in ScrollView, however I use react-native-navigation in the app. I was debugging it last night and noticed that `onPanResponderTerminate` event is fired right away once I start to swipe row. Only happens if list view is scrolled even a tiny bit. Tested in Android and it works absolutely fine there. I will keep debugging and looking for the cause. If you have any ideas or suggestions let me know. Thanks 😉

**Comment by jemise111** [comment]
@VitaliiK91 Ah okay - in that case I would search through the GH issues here for "navigation" and see if any of the responses help you. Some people have found ways to make the gesture handlers play nice together but I don't know of any off the top of my head

**Comment by VitaliiK91** [comment]
Found the root of the problem (at least for my case). Sharing in case someone runs into similar issue. After more debugging I noticed that issue happens not when list is scrolled just a bit but when it is scrolled almost to the end (i.e. last item is seen). After wrapping the component in the `<SaveAreaView/>` the problem disappeared. I am pretty sure this can only happen on the devices with notch (in my case iPhoneX, 11 etc...) @jemise111 Thanks for the great library and help. Cheers 🤓

**Comment by jemise111** [comment]
Excellent @VitaliiK91 glad you found a solution

**Comment by nenjamin2405** [comment]
@VitaliiK91 Many thanks for your solution, I'm having the same issue just like you using react-native-navigation

**Comment by elirangoshen** [comment]
how you solve it ? i trie to use i have it both on android and ios ..
i tried to use SafeAresView but it doenst seems to work
thats really big issue so i wonder
