### ISSUE TITLE
Have exclusive swipe when using standalone SwipeRow

### ISSUE THREAD

**Issue by peterdev6** [jemise111/react-native-swipe-list-view#169]
Is there any way I can only have one row open when using SwipeRow component in my Flatlist component?

**Comment by jemise111** [comment]
Hey @peterdev6 thanks for the question. I assume you're talking about the behavior in the SwipeListView whereby when you open a row it closes the previously opened row before opening the next one. 

In order to achieve that we just have to implement some of the code from the SwipeListView into your FlatList.

This should get you on the right track:

```
class App extends Component {

	constructor(props) {
		super(props);
		this._rows = {};
		this.openRowId = null;
		this.state = {
			basic: true,
			listViewData: [
				{
					id: 0,
					text: 'Number 0',
				},
				{
					id: 1,
					text: 'Number 1',
				},
				{
					id: 2,
					text: 'Number 2',
				},
				{
					id: 3,
					text: 'Number 3',
				},
			]
		};
	}

	onRowOpen(id) {
		if (this.openRowId) {
			this._rows[this.openRowId].closeRow();
		}
		this.openRowId = id;
	}

	renderItem = (data) => {
		return (
			<SwipeRow
				ref={ref => this._rows[data.item.id] = ref}
				leftOpenValue={75}
				rightOpenValue={-75}
				onRowOpen={_ => this.onRowOpen(data.item.id)}
			>
				<View style={styles.standaloneRowBack}>
					<Text style={styles.backTextWhite}>Left</Text>
					<Text style={styles.backTextWhite}>Right</Text>
				</View>
				<View style={styles.standaloneRowFront}>
					<Text>{data.item.text}</Text>
				</View>
			</SwipeRow>
		);
	}

	render() {
		return (
			<View style={styles.container}>
				<FlatList
					data={this.state.listViewData}
					renderItem={this.renderItem}
					keyExtractor={(item, index) => item.id}
				/>
			</View>
		);
	}
}
```

The above code produces this:

![](http://g.recordit.co/TSQO6Pflio.gif)

Which I think is what you're looking for.

You can refer to how I've implemented the SwipeListView from a ListView.. and apply that to your FlatList until a SwipeFlatList is supported by default here..

Let me know if you have any questions, thanks!

**Comment by peterdev6** [comment]
@jemise111 Thank you so much for your detailed response. You are the man!

**Comment by baicuhaha** [comment]
There is something wrong with the answer upstairs
 ref={ref => this._rows[data.item] = ref}
                    rightOpenValue={-ScreenUtils.scaleSize(210)}
                    disableRightSwipe={true}
                    onRowOpen={() => {
                        if (this.openRowId) {
                            if (this.openRowId == data.item) {
                            } else {
                                this._rows[this.openRowId].closeRow();
                            }

                        }
                        this.openRowId = data.item;
                    }}>
