### ISSUE TITLE
problem with swipe list and tabs

### ISSUE THREAD

**Issue by timorss** [jemise111/react-native-swipe-list-view#189]
Hello.
my problem is i have tabs on the top of the screen.
so if i swipe, it swipes to other tab...and not the object itself.
without tabs it works well...

**Comment by jemise111** [comment]
Hey @timorss. I've run into this issue myself and unfortunately I had to turn off swipe gestures on the tab view.

I'm not sure how we could solve this from this component alone. Do you have any suggestions? If you were building both from scratch you could look at the velocity and distance of the swipe and try to determine whether the user is swiping a row or a tab but without access to your tab view I'm not sure what we can do here

**Comment by timorss** [comment]
I had to turn off swipe gestures on the tab  as well...unfortunatlly

**Comment by jemise111** [comment]
@timorss Going to close this issue. If you want a better solution I'd suggest you copy the source code from this lib into your own project and play around on this line:

https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L97

Here you can decide if the SwipeRow should take control of the swipe. I think if you return `false` in that function the tab will take control of the swipe instead of this lib. So perhaps you want to try to look at the change in distance and velocity and come up with some parameters such as: fast + short distance = row swipe, slow + long distance equals tab swipe. Or something like that...

No guarantees but maybe you can get it to behave closer to what you want.

Good luck!

**Comment by thbd** [comment]
Hi, it's been a while since this but I am still experiencing it today. 
Disabling swipe gesture on tabs would do for me but it doesn't solve the issue... Any hint ?
Thank you

**Comment by Kawaljeet-AUI** [comment]
@thbd How did you end up using it? 
I have the same problem, doesn't help with disabling tab swipe as well.

**Comment by thbd** [comment]
@Kawaljeet-AUI The thing never worked. I stopped developing and changed career, I was too fed up with nothing ever working out
