### ISSUE TITLE
swipeRow  stopLeftSwipe  props

### ISSUE THREAD

**Issue by 312362115** [jemise111/react-native-swipe-list-view#195]
```
handlePanResponderMove(e, gestureState) { 
	if (this.props.stopLeftSwipe && newDX > this.props.stopLeftSwipe) { newDX = this.props.stopLeftSwipe; }  
	if (this.props.stopRightSwipe && newDX < this.props.stopRightSwipe) { newDX = this.props.stopRightSwipe; }
}
```

this.props.stopLeftSwipe is a positive number, 
maybe `newDX  < this.props.stopLeftSwipe` is right

**Comment by jemise111** [comment]
Hey @312362115, thanks for the issue! You're totally right but I think this is more a naming issue than a code issue. I should have named the prop something like `stopLeftOpening` instead of `stopLeftSwipe`.

However at this point I'd like to keep it as is and not make the code change for two reasons. 1 - it would be a breaking change and I hesitate to do that and cause a lot of people problems. 2 - I like that the `stopLeftSwipe` value corresponds with the `leftOpenValue` and `stopRightSwipe` value corresponds with the `rightOpenValue` and I'd like to keep it that way. I'll make a note in the readme though to clarify.
