### ISSUE TITLE
RowKey undefined

### ISSUE THREAD

**Issue by dsc-ian** [jemise111/react-native-swipe-list-view#204]
I'm having an issue when I open a row, the other rows doesn't close, when I console.log the rowkey it is set to undefined. What could be the problem?

<SwipeListView
      useFlatList
      inverted={true}
      data={comments}
      renderItem={this.renderComment}
      renderHiddenItem={this.renderDelete}
      disableRightSwipe
      rightOpenValue={-75}
      previewRowKey={''}
      onRowDidOpen={this.onRowDidOpen}
/>

<img width="231" alt="screen shot 2018-04-30 at 7 47 12 am" src="https://user-images.githubusercontent.com/13307763/39412177-bdf5dc94-4c4a-11e8-9bef-da123f251a84.png">

**Comment by dsc-ian** [comment]
Also when using useFlatList the auto close of opened row is not closing.

**Comment by jemise111** [comment]
Hey @dsc-ian I think your first and second issues are being caused by the same thing. Can I see an example of what `comments` looks like?

Each object in the `comments` array should have a `key` property or if not you need to pass a `keyExtractor` prop telling it how to create the `key`. Is this the case with your example? Thanks!

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues
