### ISSUE TITLE
Flickering List in iphone X only

### ISSUE THREAD

**Issue by rf1804** [jemise111/react-native-swipe-list-view#211]
react : 16.3.1
react-native : 0.55.2
react-native-swipe-list-view : 1.1.0

Only in Iphone X, in real device as well as in simulators list flickers whenever i navigate to another screen and come back

[Video Link](https://expirebox.com/download/45b161bf441ccc5c371fa4f0658baeb3.html)

**Comment by jemise111** [comment]
Hey @rf1804 I see the flickering you're talking about but I'm not sure this is a <SwipeListView> issue. It looks like the little white bar at the bottom of the list is flickering. I would suggest swapping out the <SwipeListView> with a <FlatList> or <ListView> to isolate the problem and see if it is really a problem with this component. 

I'd be happy to help try to figure it out if you want to post some code. Thanks!

**Comment by rf1804** [comment]
Hey @jemise111 thanks for the reply, i was also not sure earlier that what is causing this flickering so first i removed fab button but that still happened, so i colored bottom tab bar as u also pointed i was also thinking that white part is of tab bar but it wasn't, den i commented the swipe list and problem does not occured, so i tried 2 3 times to check is it really coz of swipe list only and i found that whenever there is swipe list and i navigate to some screen and come back it starts flickering, i think in iphone x it is not able to get right size, it is constantly calculating and flickering for 10 to 20 seconds and den it becomes normal.

**Comment by jemise111** [comment]
Hm that's very strange. Did you try swapping out the <SwipeListView> with a <FlatList> to isolate the problem?

You could also try setting a fixed height on the List, or playing with the `initialListSize` prop and setting it to a higher value than the default.

**Comment by lovebehl** [comment]
@jemise111 as u said i tried using `<FlatList>` to check is it a bug of `<SwipeListView>` or not, but using `<FlatList>` also it occurs means either it's because navigation library `react-native-navigation` or with `react-native`.
I've opened a issue in `react-native-navigation` hope to solve it soon.

> `initialListSize` prop did the partial work, it does not flicker now but that white part comes up on screen push and den goes down on next screen push

i guess the problem was it is not getting the proper height to calculate number of rows to render and coz of iphone X padding it was flickering as it was confused between actual height

**Comment by rf1804** [comment]
@jemise111 as u said i tried using `<FlatList>` to check is it a bug of `<SwipeListView>` or not, but using `<FlatList>` also it occurs means either it's because navigation library react-native-navigation or with react-native.
I've opened a issue in react-native-navigation hope to solve it soon.

> `initialListSize` prop did the partial work, it does not flicker now but that white part comes up on screen push and den goes down on next screen push

i guess the problem was it is not getting the proper height to calculate number of rows to render and coz of iphone X padding it was flickering as it was confused between actual height

**Comment by jemise111** [comment]
Interesting.. well if you don't mind since this isn't an issue with this library I will close this. If you find any more issues feel free to re-open.

If I were you I would try to set fixed heights on everything - the main screen, the tab bar, and the list. Maybe some combination of fixed heights + `initialListSize` can do the trick. Good luck!

**Comment by rf1804** [comment]
@jemise111 i tried giving fixed height but no luck, even for to find out what is that white part i've even given background color to every component but i've not able to find from where that white part comes.

**Comment by steverob** [comment]
Any updates on this?

**Comment by rf1804** [comment]
just give height: '100%' instead of flex:1 of main container, somehow it worked
