### ISSUE TITLE
Wrong params in renderItem callback

### ISSUE THREAD

**Issue by pgonzalez-santiago** [jemise111/react-native-swipe-list-view#219]
I am using:
"react-native": "0.48.3"
"react-native-swipe-list-view": "^1.3.0"

I want to open a row when a click event is triggered but I can not do it. 

This is my code:

```
      <SwipeListView
        useFlatList
        data={topics}
        keyExtractor={item => item._id}
        renderItem={this._renderRow}
        renderHiddenItem={ (data, rowMap) => (
          <Text>Hidden Item</Text>
        )}
        leftOpenValue={75}
        rightOpenValue={-75}
        disableRightSwipe
      />
```

In the documentation I see:
```
    renderItem={ (rowData, rowMap) => (
        <View>
            <Text>I am {rowData.item.text} in a SwipeListView</Text>
        </View>
    )}
```

but when I inspect the params of the renderItem callback what I get is: 

`{item: {…}, index: 0, separators: {…}}` instead of `(rowData, rowMap)`

so I can not access to the openRow functionality. Any ideas?

Thank you.

**Comment by jemise111** [comment]
Hey @pgonzalez-santiago I think you might be having the same problem as another issue ( #220 ). The issue here is that the rowMap is populated at a time after the component is rendered once (since it is based on `ref`s. In order to open a row when it is touched try doing what I wrote here:

https://github.com/jemise111/react-native-swipe-list-view/issues/220#issuecomment-398678246

And if this doesn't' solve your issue please let me know.

**Comment by jemise111** [comment]
Closing as inactive, please reopen if you still have issues
