### ISSUE TITLE
Content height calculation of hidden view is off if image is first child in visible view

### ISSUE THREAD

**Issue by ppetrick** [jemise111/react-native-swipe-list-view#244]
First off, fantastic job on this lib. It's really useful. 

I'm encountering a small issue with the hidden view height calculation (as shown below). Notice that the hidden views don't stretch the full height of the visible views unless the text contained in the visible view takes up more space than image within it. 

As far as I can tell, this has something to do with the first component in the visible view being an image (from from '@expo/vector-icons'). I poked around in the code and traced it to the optimization when calling onContentLayout in renderRowContent. If I call that function every render (effectively overriding your performance optimization), it calculates the height correctly. Not sure if there's something I should do differently here or not, as I'm not very well versed in nativeEvents. Or am I just stuck running recalculateHiddenLayout?

![screen shot 2018-10-19 at 5 11 17 pm](https://user-images.githubusercontent.com/309619/47248892-87c8cc80-d3c2-11e8-88e3-8e45fa3849b5.png)
![screen shot 2018-10-19 at 5 11 57 pm](https://user-images.githubusercontent.com/309619/47248893-87c8cc80-d3c2-11e8-9d46-448cfb1b864f.png)

The visible view code (and styles)
```

<View style={styles.container}>
  <MaterialIcons name='group' size={30} />
  <View style={styles.textContainer}>
    <Text style={styles.title}>{this.props.item.name}</Text>
  </View>
</View>
```
```
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.light,
    marginLeft: Spacing.small,
    marginRight: Spacing.small,
    marginBottom: Spacing.xsmall,
    paddingLeft: Spacing.small,
    paddingRight: Spacing.small,
    paddingTop: Spacing.medium,
    paddingBottom: Spacing.medium,
    borderRadius: 10
  },
  textContainer: {
    flex: 1,
    paddingLeft: 10
  },
  title: {
    fontSize: 19
  },
}); 

```

**Comment by jemise111** [comment]
Hey @ppetrick sorry for the delay in responding. 

Using `recalculateHiddenLayout` isn't a huge deal. I would enable that prop and see if you have any noticeable performance issues. For large lists it could be problematic but I doubt it would be.

Another option might be to calculate the height of the row before it is first rendered and hard code the height so the hidden row infers the correct height on the first render.

Going to close this since `recalculateHiddenLayout` is a viable solution for you but please reopen if you have other questions, thanks!
