### ISSUE TITLE
hiddenHeight and hiddenWidth calculated wrong in Windows

### ISSUE THREAD

**Issue by Lion-HC** [jemise111/react-native-swipe-list-view#267]
What is this code fore?
`	onContentLayout(e) {
		this.setState({
			dimensionsSet: !this.props.recalculateHiddenLayout,
			hiddenHeight: e.nativeEvent.layout.height,
			hiddenWidth: e.nativeEvent.layout.width,
		});`

When I remove this code - everything is fine.
Current styling 
`hidden: {
		zIndex: 1,
		**bottom: 0,**
		left: 0,
		overflow: 'hidden',
		position: 'absolute',
		**right: 0,**
		top: 0,
	},`
or 
`width: '100%',
height: '100%',`
seems to be quite enough for correct hidden layout.
Was there any issue that this code fixes?

**Comment by jemise111** [comment]
@Lion-HC Yes this allows for a default style that correctly positions the hidden row. TBH it has been a couple years since that original code was written and I don't remember what it fixed at the time.

Happy to look at a PR if you'd like to include a prop that lets the client disable those styles or passes its own :)
