### ISSUE TITLE
Disable row entry animation?

### ISSUE THREAD

**Issue by Slapbox** [jemise111/react-native-swipe-list-view#272]
When a row first appears it bounces left and then returns to its start position. I can't find any option to disable this though? Am I overlooking something obvious?

Thanks for this great project!

**Comment by jemise111** [comment]
Hey @Slapbox, I think I found the issue here. By default it should not do a preview animation but I think there's a bug if you do not provide a `key` for each object in your data array or a `keyExtractor`. Could you confirm that adding one of those fixes the issue? And I'll release a fix shortly after that

Thanks!

**Comment by Slapbox** [comment]
@jemise111 Brilliant! Thanks so much! Adding a `keyExtractor` definitely fixes the issue. 

Do you need to add a code fix somewhere or is it at simple as updating the ReadMe? My items did not have a `key` property, but rather a `uuid` property.

**Comment by jemise111** [comment]
@Slapbox Excellent, I wouldn't worry about the readme - I'll release a fix for those who don't pass a key. Going to close this, thanks!
