### ISSUE TITLE
onPress method called at render

### ISSUE THREAD

**Issue by benoitvallon** [jemise111/react-native-swipe-list-view#3]
If I do something like this, my `onPress` method gets call for every rows at render.

```js
renderHiddenRow={(rowData, secId, rowID) => (
  <TouchableHighlight onPress={this._handleRemoveIdea(rowID)} style={styles.rowBack}>
    <Text style={styles.rowBackText}>Delete</Text>
  </TouchableHighlight>
)}
```

**Comment by jemise111** [comment]
I think this is because you're actually calling the function when the onPress handler is bound to the TouchableHighlight. Could you give something like this a try:

`<TouchableHighlight onPress={ _ => this._handleRemoveIdea(rowID) } style={styles.rowBack}>`

Let me know if that does the trick otherwise I'll investigate further

**Comment by benoitvallon** [comment]
Thanks, I will try that tonight and will let you know

**Comment by benoitvallon** [comment]
It works great. thanks

**Comment by vijayperlakota** [comment]
@jemise111 your solution works great :) Thanks a lot

**Comment by privateOmega** [comment]
@jemise111 Thanks a lot for your solution and its explanation.

**Comment by hasanugr** [comment]
@jemise111 It works, thanks a lot. :)
