### ISSUE TITLE
Using SwipeRow in ListView

### ISSUE THREAD

**Issue by npomfret** [jemise111/react-native-swipe-list-view#30]
I want to use a SwipeRow in a ListView rather than use a SwipeListView because i want different behaviour on different rows. Some for example should not be swipeable.

The behaviour I'm seeing is that the right-swipe works fine, but the left-swipe doesn't.  After releasing the left-swipe, the view immediately switches as if I'd done a right-swipe.

**Comment by cmdillon** [comment]
hi, i was wondering how i can make "rightOpenValue" value dynamic? i tried adding "ref=" to a "View" element, and then doing something like: https://github.com/facebook/react-native/issues/953 
but that didn't work seems the "ref" is not available inside "renderHiddenRow". any ideas or examples would be appreciated.

**Comment by jemise111** [comment]
Hey @npomfret. So I tried to replicate your issue but I can't. I think what may be happening is as you're swiping left you're also swiping up causing the ListView to scroll which causes the row to close. This is handled if you're using the SwipeListView since I have access to all scrolling behavior and can determine what is a scroll vs a swipe.

For this reason I wouldn't recommend using standalone SwipeRow's inside of Scrollable Views.

To achieve what you're talking about the SwipeListView needs to handle SwipeRow's with different behavior. This would also address #31. I have some ideas but haven't had time, I'll try to get to this asap. PR's are always welcome 😃 .

I tried to show what I mean below. Let me know if this makes sense or I'm missing the issue.

Here's the code and screengrab:

```
<View style={styles.container}>
	<ListView
		style={{flex: 1}}
		dataSource={this.ds.cloneWithRows(this.state.listViewData)}
		renderRow={ data => (
			<SwipeRow
				leftOpenValue={75}
				rightOpenValue={-75}
			>
				<View style={styles.standaloneRowBack}>
					<Text style={styles.backTextWhite}>Left</Text>
					<Text style={styles.backTextWhite}>Right</Text>
				</View>
				<View style={styles.standaloneRowFront}>
					<Text>I'm SwipeRow {data}</Text>
				</View>
			</SwipeRow>
		)}
	/>
</View>
```

![](http://g.recordit.co/vWm3sltPjx.gif)

**Comment by npomfret** [comment]
Thanks for the reply.  If i get some time I'll take a look at implementing per row behaviours

**Comment by jemise111** [comment]
@npomfret Npm install the latest version and check out the docs [here](https://github.com/jemise111/react-native-swipe-list-view#per-row-behavior) for dynamic values on SwipeRows.

The example now shows how to disable swiping on only some rows.

Let me know if you have any further problems or questions!

**Comment by npomfret** [comment]
Perfect, thanks!
