### ISSUE TITLE
onScroll Animated.event(...)

### ISSUE THREAD

**Issue by MikeMajara** [jemise111/react-native-swipe-list-view#331]
I just migrated SectionList list I had with swipeable rows to this SwipeableListView with SwipeRow. So far so good. Until my Animated.event(...) I had in my list onScroll prop breaks the list. So all is working better than expected, and easy, but this one thing... So first things first congrats.

I have gone through your code and tried to modify it so maybe I could do a PR. But no success at all. I just started a few weeks ago with RN, it may be (1) my lack of understanding, (2) that it is not possible at all the way the library is set right now, or even (3) not possible because of RN and the interaction between parent and child component.

I have an animated header in my component that has an animated opacity depending on the scroll offset of the list as follows.

```js
class MyContainer extends React.Component {
  constructor(props) {
    super(props);
    // ...
    this.state = {
      scrollY: new Animated.Value(0),
    };
    // ...
  }

  // ...
  render() {
    return (
      <View>
        <Animated.View
          style={{
            // ...
            opacity: this.state.scrollY.interpolate({
              inputRange: [0, 30, 100],
              outputRange: [0, 0, 1],
            }),
          }}
        >
          <Text style={iOSUIKit.bodyEmphasized}>Operations</Text>
        </Animated.View>
        <SwipeListView
          useSectionList
          onScroll={Animated.event(
            [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
            { useNativeDriver: true } // <-- Add this
          )}
          // ...
          renderItem={({ item, index, section }) => (
            <SwipeRow>
            </SwipeRow>
          )}
        />
      </View >
    );
  }
}
```

(1) Suggestions?
(2,3) If it is indeed posible, would it be to hard to change, if so how? Suggestions?

A fourth option would be to avoid using `SwipeListView` and including straight away `SwipeRow` in my Animated.SectionList, but then I have had some problems keeping all your functionality out of the box (such as avoiding scroll when swiping row, or closing open rows on scroll, and similar functionalities).

**Comment by jemise111** [comment]
Hey @MikeMajara this is a tricky one. It turns out if you add the `{ useNativeDriver: true }` config to the `Animated.Event` it no longer returns a function, it instead returns an object. That's what is breaking your scrolling behavior. If you remove the `{ userNativeDriver: true}` from your onScroll event it will work just fine.

I would have a read through this issue to learn more: https://github.com/facebook/react-native/issues/16250

They suggest using an Animated.Scrollview (or an Animated.Flatlist in this case if it exists (?)). You could potentially use a SwipeListView with the `renderListView` prop to render your own custom listview, I'm not entirely sure it'd work and I'm sorry but just don't have the time to play around with all that right now. Try the suggestion above and if your app is still performant I'd just go with that

**Comment by MikeMajara** [comment]
Had to go on Holidays and switched to a different task mean while. Sounds about right dropping the `useNativeDriver` (I already had some problems with other animations solved this way). It never occurred to me to try this. So I'll comment back as soon as I can try to let you know if it worked alright that way.
