### ISSUE TITLE
First rows on iOS not opening

### ISSUE THREAD

**Issue by flowridr** [jemise111/react-native-swipe-list-view#346]
Using React native 0.60.5 and react native navigation 3.2.0. The rows on first screen are not able to open (they are moving a bit but dont stay open). The swiping on rows after first screen is working fine. On Android everything works well.

**Comment by jemise111** [comment]
Hey @flowridr as with all issues involving react native navigation there are a ton of factors that could be contributing to this problem. To be able to debug this I'd really need a code sample that would allow this to reproduce the issue on my end, or better yet a repository I could look at on my machine that demonstrates the problem.

In the meantime issues with navigation libraries are usually caused by the nav library capturing the swipe gestures. You can try disabling them to see if that is indeed the cause of your issues

**Comment by jemise111** [comment]
Closing as inactive
