### ISSUE TITLE
Hidden Item invisible sometime.

### ISSUE THREAD

**Issue by superhos** [jemise111/react-native-swipe-list-view#373]
Most of time is normal. But sometime the hidden item was disappear. Has anyone ever been in the same situation with me? Or any suggestion?

**Comment by superhos** [comment]
I have also output the `HiddenComponent` parameter in `renderCell`, the data is correct.

**Comment by jemise111** [comment]
Hi @superhos these issues are very difficult to figure out without some example code or a gif showing the issue. Can you please try to provide some more info like that? Thank you

Only thing I can think of off the top of my head that is a somewhat common issue is using a TouchableOpacity instead of a TouchableHighlight as your renderItem

**Comment by superhos** [comment]
I used the common demo code of the guide page.
react native version is 0.52.2
react version 16.2.0

It's really hard to identify the cause of the problem. I will debug the code and reopen the issue if any progress.

**Comment by eladgel** [comment]
Same here

**Comment by markmoomoo** [comment]
@eladgel @superhos @jemise111 this bug totally replicable, and happens when I added quickaction list for ios, when I start from quick action, the hidden part disappears

after I dig deep to the source code, I found the `
<View
                style={this.props.style ? this.props.style : styles.container}
            >
                <View
                    style={[
                        styles.hidden,
                        {
                            height: this.state.hiddenHeight,
                            width: this.state.hiddenWidth,
                        },
                    ]}
                >
                    {this.props.children[0]}
                </View>
                {this.renderRowContent()}
            </View>`
in swiperRow.js
the this.state.hiddenHeight and this.state.hiddenWidth are 0, that's why they disappeared
