### ISSUE TITLE
Wrong row position on SwipeRow / Scrolling while swiping

### ISSUE THREAD

**Issue by FranciscoCHT** [jemise111/react-native-swipe-list-view#396]
**Describe the bug**
I'm using only SwipeRow, and when I open a row with left swipe and then close, the row seems to bug itself, because then when I swipe the row again (left or right) it sets it's position like it's closing. **This happens only with the rows I open. Once opened (and closed), keeps happening that bug on the row.**

And, when I swipe, vertical scroll doesn't disable, so when I open a row and swipe a little up at the same time, the row closes or open (finishing its animation) making it very difficult to open rows. I don't know if there is a way to disable this.

I already tried solutions #306 #311 

My swiperow code.
```
<SwipeRow 
          rightOpenValue={-75} 
          style={styles.swipeRow}
          disableRightSwipe={true}
          //closeOnRowPress={true}
>
```

**To Reproduce**
1. Use SwipeRow.
2. Swipe a row to the left and open.
3. Close row and swipe again on the same row.
4. Swipe row to the left and up at the same time.

**Screenshots**
First part shows the vertical scrolling on swipe.
Second part shows the position bug when swipe on opened rows.
![83327395_470211500588233_4541280861516988416_n](https://user-images.githubusercontent.com/9930150/72761309-66085780-3bba-11ea-9703-6fe3ba4ba224.gif)

**Environment (please complete the following information):**
 - OS: Android
 - RNSLV Version: 2.1.3
 - RN Version: 0.61.5

**Comment by jemise111** [comment]
@FranciscoCHT I just tried in my example and I'm not experiencing the same issue as you using a standalone SwipeRow.

I suspect that issue, as well as your second issue, is due to the fact that you are using a SwipeRow in a scrolling list and the gesture recognizers for the two components are conflicting. Since you are not using a SwipeListView the SwipeRow has no idea when the list is being scrolled and therefore cannot deal with the interactions.

You'll have to handle the interactions between the gesture recognizers or you can try using a SwipeListView instead

**Comment by jemise111** [comment]
Closing as inactive
