### ISSUE TITLE
Remove misleading readme section?

### ISSUE THREAD

**Issue by nferrara100** [jemise111/react-native-swipe-list-view#415]
The following section of the readme was misleading in my case: 

#### Note:

If your row is touchable (TouchableOpacity, TouchableHighlight, etc.)  with an ```onPress``` function make sure ```renderItem``` returns the Touchable as the topmost element.

GOOD:
```javascript
renderItem={ data => (
    <TouchableHighlight onPress={this.doSomething.bind(this)}>
        <View>
            <Text>I am {data.item} in a SwipeListView</Text>
        </View>
    </TouchableHighlight>
)}
```
BAD:
```javascript
renderItem={ data => (
    <View>
        <TouchableHighlight onPress={this.doSomething.bind(this)}>
            <Text>I am {data.item} in a SwipeListView</Text>
        </TouchableHighlight>
    </View>
)}
```

## Rational

If you have a `<TouchableOpacity>` instead of a `<TouchableHighlight>` as in the example above you need to place the `<TouchableOpacity>` inside a `<View>` with a background color so that the swipe row does not get shown throw your main row. Swipe rows are stored under the main row, so reduced opacity without something between them results in unwanted transparency.

I'm curious if I should create a pull request to remove this note, since it didn't seem to affect me, or if there is a good reason to keep it. If there is a good reason to keep it, then when is it acceptable to use an enclosing `<View>`  to set the background color?

For details the on the issue setting background color in a containing `<View>` solves, please see #232

**Comment by nferrara100** [comment]
Curious what you think, @jemise111

**Comment by jemise111** [comment]
Hi @nferrara100 so the reason the `Touchable` has to be the topmost component is because when I render the row I have to run my own `onPress` callback in addition to whatever `onPress` the client wants to run. See here: https://github.com/jemise111/react-native-swipe-list-view/blob/master/components/SwipeRow.js#L441

If you have a `Touchable` inside of a `View` I think it would break certain functionality, such as the `closeOnRowPress` action that happens by default.

The issue with a transparent row is definitely a limitation of this setup, which is why I encourage people to use a `TouchableHighlight` instead of `TouchableOpacity`.

So I think the note should be left in place (it has helped several people who have posted issues). However if you want to add a section under if for dealing with opacity issues please feel free and I'll happily take a look, thanks!

**Comment by jemise111** [comment]
Closing but please re-open if more work needs to be done here, thanks!
