### ISSUE TITLE
closeOnRowPress do not work on standalone SwipeRow

### ISSUE THREAD

**Issue by AzatFMS** [jemise111/react-native-swipe-list-view#42]

**Comment by jemise111** [comment]
Hey @AzatFMS thanks for reporting but I'm not seeing any issues. I've tried it on RN 0.28 and 0.29. If you could post device, version numbers, and the code you're using I can look into this further.

![](http://g.recordit.co/XM9wPubeTC.gif)

**Comment by AzatFMS** [comment]
`<SwipeRow
            rightOpenValue={-70}
        >
            <View style={styles.rowBack}>
                <TouchableOpacity onPress={this.doSmth}>
              <Text>Click here but swipe not closing</Text>
       </TouchableOpacity>
            </View>
            <View >
            </View>
        </SwipeRow>`

Something like this.

**Comment by jemise111** [comment]
Hey @AzatFMS without seeing the rest of the code it's tough to tell what the problem is. But in the example in ```example.js``` is set up the same way and is working fine. 

In the example I just splice the dataSource's array at the index of the rowId for whichever row is pressed. And then set the state for the dataSource to be the new array. 

Have a look here https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L98 and here https://github.com/jemise111/react-native-swipe-list-view/blob/master/SwipeListExample/example.js#L27 for the working example.

Let me know if you have any questions. If it's still not working please post the rest of your code and I'd be happy to look at it. Thanks!

**Comment by AzatFMS** [comment]
Oh, vfyually closing rows is what i need. Thanks!

**Comment by coderdave** [comment]
Just so I understand this, `closeOnRowPress` doesn't work when using `SwipeRow`, you have to close it manually?

**Comment by chudaotrucnhan** [comment]
set a ref in SwipeListView and call safeCloseOpenRow when onPress in SwipeRow.

**Comment by jobala** [comment]
@chudaotrucnhan 

It would be nice if you could post an example
