### ISSUE TITLE
Swipe gesture getting disabled for few minutes in android.

### ISSUE THREAD

**Issue by SmritiSYadav** [jemise111/react-native-swipe-list-view#463]
In android, whenever I land to the screen swipe gesture is disabled for few minutes and getting this error even though I hardly have 25-30 items in my sectionlist.

**Error:** _"VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc."._

**Comment by jemise111** [comment]
Hey @SmritiSYadav sorry but this is certainly not an issue with this library (since there is just a basic SectionList underneath it all). This is a warning being thrown by react native itself. There's a doc here that has some strategies for fixing rendering problems, perhaps your SectionList is re-rendering too often? I would try to use some optimization tips here and get that warning to go away:

https://reactjs.org/docs/optimizing-performance.html#virtualize-long-lists
