### ISSUE TITLE
UnCaught Error: toValue on android after swipe

### ISSUE THREAD

**Issue by z-Javier-w** [jemise111/react-native-swipe-list-view#502]
recieveing this error everytime i swipe on my android device

heres my code:

import {SwipeListView,SwipeRow} from "react-native-swipe-list-view"
         <View style={styles.list}>
          <SwipeListView
            data={todos}
            renderItem={({item})=> (
              <TodoItem item={item} pressHandler={pressHandler}/>
            )}
            renderHiddenItem={()=>{
              return(<View style={styles.rowBack}>
                <View style={styles.rowBackGreen}><Text>Left</Text></View>
                <View style={styles.rowBackRed}><Text>Left</Text></View>
              </View>)
            }}
            leftActivationValue={15}
            rightActivationValue={15}
            onLeftAction={()=>ToastAndroid.show("Left", ToastAndroid.SHORT)}
            onRightAction={()=>console.log("Right")}
          />
        </View>

**Comment by SallyHabib97** [comment]
I have the same issue

**Comment by MedRedha** [comment]
Same here too :(

**Comment by NilsKrause** [comment]
This happens because in `handleLeftSwipe` and in `handleRightSwipe` in `SwipeRow.js` the `rightActionValue` / `leftActionValue` is used to set the `toValue` for `Animated.spring` (called in `manuallySwipeRow`). 
see for example: https://github.com/jemise111/react-native-swipe-list-view/blob/2f5cdec5ebd6ee320c42e4c9f477d1f072ecb40c/components/SwipeRow.js#L459

These props are optional and aren't initialised. Hence the crash. Workaround: set the property `rightActionValue` and/or `leftActionValue` until someone patches the behaviour.

**Comment by jemise111** [comment]
Hey @z-Javier-w just adding those props above and running this on Android I'm not seeing any errors, can you please provide a reproducible example I can run on my end?

@NilsKrause Do you have an idea on how to fix this? Would love to look at a PR if you could, thanks!

**Comment by wennaspeedy** [comment]
> This happens because in `handleLeftSwipe` and in `handleRightSwipe` in `SwipeRow.js` the `rightActionValue` / `leftActionValue` is used to set the `toValue` for `Animated.spring` (called in `manuallySwipeRow`).
> See for example:
> 
> https://github.com/jemise111/react-native-swipe-list-view/blob/2f5cdec5ebd6ee320c42e4c9f477d1f072ecb40c/components/SwipeRow.js#L459
> 
> These props are optional and aren't initialised. Hence the crash. Workaround: set the property `rightActionValue` and/or `leftActionValue` until someone patches the behaviour.

It works, thank you!

**Comment by LFMAKER** [comment]
any update?

**Comment by LFMAKER** [comment]
I have the same issue

**Comment by kipperlhp** [comment]
+1 have the same issue

**Comment by dburdan** [comment]
@jemise111 This crash occurs when [this line](https://github.com/jemise111/react-native-swipe-list-view/blob/2f5cdec5ebd6ee320c42e4c9f477d1f072ecb40c/components/SwipeRow.js#L479) is called and `toValue` is `undefined`. As mentioned above, that can happen when `leftActionValue` or `rightActionValue` are not passed as props due to .

Maybe a simple solution would falling back to `0` if `toValue` is undefined? If so, I can create a PR.

**Comment by jemise111** [comment]
Hey guys, sorry for the delay and thanks for the proposed solution @dburdan!

There was a default in place when using a SwipeListView, but no default in place when using individual SwipeRows, hence my confusion. This will be fixed in the next release
