### ISSUE TITLE
Delete only when touch is released

### ISSUE THREAD

**Issue by simplenotezy** [jemise111/react-native-swipe-list-view#573]
I looked at the example here: https://snack.expo.dev/@jemise111/react-native-swipe-list-view, specifically `swipe_to_delete.js`.

1. How can the example know that the user released the finger? Naturally, you don't want to trigger a deletion event, before the finger is released. Say the user just swiped, and then changed his mind, and moves the swipe "back" to its position. The demo takes care of this perfectly, I just don't seem to be able to replicate a similar approach in my project - nor do I understand how the example actually handles it. I know the example works, I just don't know how.

2. What's the reason behind: `if ( value < -Dimensions.get('window').width)`? I would perhaps write it as: `if ( value > (Dimensions.get('window').width / 2) ) {`, so a deletion only should be triggered if the item was swiped more than half way through the screen

**Comment by simplenotezy** [comment]
@jemise111 You must be busy, but could you point me in any direction? As a workaround I experimented around with using state to detect onPressOut, however, as soon as you start to slide, onPressOut (on touchablehighlight) is fired.

**Comment by simplenotezy** [comment]
OK, so I managed to use `swipeGestureBegan` and `swipeGestureEnded` and then only trigger the "delete" event when `isSwiping` is false.

          swipeGestureEnded={() => setIsSwiping(false)}
          swipeGestureBegan={() => setIsSwiping(true)}

However, it's still a mystery how the demo works, without using a state like I had to do, so would really appreciate an answer as to how it really works.

**Comment by jemise111** [comment]
Hi @simplenotezy, apologies for the delay. I'm having a hard time these days finding free time to respond to GH issues.

The way the demo works is as follows:

The trigger for the delete animation has nothing to do with the user removing their finger from the screen. The lib itself takes care of deciding what to do when the user lifts their finger (e.g. swipe fully open if row is opened more than 50%, other close, etc)

Let's say the user opens the row 60% of the way across and then lifts their finger. The lib decides to open the row fully, so an animation begins to set the translateX value of the row to `-Dimensions.get('window').width` (the `rightOpenValue`. Because this is a spring animation the row's translateX value _actually_ goes slightly beyond the `rightOpenValue` (i.e. slightly less than `-Dimensions.get('window').width`). Since I'm tracking the value every time it changes in the `onSwipeValueChange` prop, I know exactly when that happens and I know that means the row was just fully opened, and I can go ahead and run my delete animation. 

The answer to twofold. First off, the translateX value of the row will be a negative number if the row is swiping left and a positive number if it's swiping right. In this example a fully opened row will have a translateX value of `-Dimensions.get('window').width`. If this row were to open fully to the right, it's translateX value would be a positive number, `Dimensions.get('window').width`. Secondly, we don't want to divide anything by 2 because, like I said above, we only trigger the delete animation once the _**open this row completely**_ animation has finished.

I can't tell if that was a clear explanation or not. If not let me know what doesn't make sense and I'll try to get back to you quickly, thanks!

**Comment by jemise111** [comment]
Oh and if this does answer your question please close the issue, thanks!

**Comment by simplenotezy** [comment]
@jemise111 It definitely makes a lot of sense; thank you. Based on your input I've managed to tweak my app to perform even better, so thanks.

I'll close the issue. And oh, may I suggest you perhaps enable "Discussions" for your repo? Perhaps that would help close a lot of issues that's basically just questions like mine.

**Comment by jemise111** [comment]
@simplenotezy sure why not, I enabled it!
