### ISSUE TITLE
Question, are you no longer doing library management?

### ISSUE THREAD

**Issue by jihoon8730** [jemise111/react-native-swipe-list-view#628]
I'm concerned that the update frequency is unreasonable.

**Comment by jemise111** [comment]
Hey @jihoon8730 I'll direct you to a previous comment I made about maintaining this lib [here](https://github.com/jemise111/react-native-swipe-list-view/issues/606#issuecomment-1242851534)

Status is mostly unchanged since then. I try to pick this up and work on it from time to time but I still just don't have the bandwidth these days
