### ISSUE TITLE
Close opened row is there any other ways when delete one row in listview?

### ISSUE THREAD

**Issue by sharingjingang050241** [jemise111/react-native-swipe-list-view#71]
@jemise111 
when I open one row ,there is  a delete-button .And I touch button to delete this row,its not closed when row in not end of listview .

Now ,how to close row which be opened voluntarily,not press to close and slide to close.Thanks

**Comment by sharingjingang050241** [comment]
![1](https://cloud.githubusercontent.com/assets/20335157/19847320/0f23b212-9f81-11e6-8391-c55e610982c2.png)
![2](https://cloud.githubusercontent.com/assets/20335157/19847319/0f1fd516-9f81-11e6-83e1-955768ca0e0a.png)
![3](https://cloud.githubusercontent.com/assets/20335157/19847321/0f2451e0-9f81-11e6-97a9-32f6f52de99b.png)

**Comment by jemise111** [comment]
Hey @sharingjingang050241 hm I'm not sure what's going. If you follow the `SwipeListExample/example.js` file it's working just fine with deleting rows and closing the deleted ones. Here's a GIF to show what the behavior is in the example:

http://g.recordit.co/0YGBMDeiLi.gif

If you still can't get it to work please reopen this issue and paste some code you're using to do the deleting, and I'll be happy to take a closer look, thanks!

**Comment by Jaafar-abusair** [comment]
+

**Comment by bhoomika911** [comment]
I have same issue.I used SwipeRow in my project.Another solution that i found is to use SwipeListView.But sometime it creates problem in rendering rows.Sometimes some of rows getting rendered and other portion of the screen remains blank.When I just scroll,all rows getting rendered.So I avoid to use that solution and remains on SwipeRow to render my list.

Please any one can help?

**Comment by chudaotrucnhan** [comment]
@sharingjingang050241 just set ref={'swipeListView'} in SwipeListView, and call this.refs.swipeListView.safeCloseOpenRow(); when you Press on Delete Button

**Comment by IamStephan** [comment]
I know this is somewhat late but if anyone is still experiencing this issue, it's because the key that is used to identify the row is not correctly defined. Make sure if you are using the keyExtractor that it is not returning an undefined value or something

**Comment by thanhluantl2304** [comment]
hey @lamStephan, I still face this problem. keyExtractor I got from index so can not be undefined or something but still not working! Please help!

**Comment by IamStephan** [comment]
Hey @thanhluantl2304, haven't worked with this library in some time. Mainly because it tends to be hard for users to identify this feature unless it is specifically shown to them.

This is purely based on memory and if you can provide a code snippet that will be helpful. I think what's happening is that when the user opens a list item the framework uses the key to know what item is open after a state update. The problem with this and using the index as a key is that when the item is removed the index values change for all the items below that deleted row. So when the state updates the lower row gets the old index of the deleted item. Meaning the framework still believes that the delete row exists and it should be kept open.

Short answer: Use the keyExtractor but use unique values and not the index of the item. Maybe a id. If I remember correctly, my list did not have unique ids so what i did was use the Math.random + the index. Try to avoid this since you'll lose references to the rows and can really do anything to them with your code (I think).

**Comment by thanhluantl2304** [comment]
Ok, i got this. You saved my life! Thank you very much!^^

**Comment by muhammadtaha1998** [comment]
@IamStephan fixed the row closing issue thanks to you. There is also another problem I am facing. Deleting the last row leaves a little of the deleted row hidden delete button. It show like a little line. I have attached the image. Please give them a look. Look at the the little red line that stays after the item is deleted.

![Screenshot_20200910-161325](https://user-images.githubusercontent.com/43718674/92728635-86279980-f38a-11ea-9bbc-4ec1f3e09aa9.png)

![Screenshot_20200910-161331](https://user-images.githubusercontent.com/43718674/92728519-43fe5800-f38a-11ea-90c0-6556c815de7a.png)
